#!/bin/bash

TOPDIR=$(dirname "$0")

source "$TOPDIR/arg_parser.sh"

CONF='
    {
     "name":
       {"name":"name",
        "short": "n",
        "required": "True",
        "help": "Name of the something"
       },
     "option":
       {"name":"option",
        "short": "o",
        "default": "default_o",
        "help": "This is manual for this option"
       }
    }'


WORKDIR="${TOPDIR}"
arg_parser "${CONF}" "$*"

echo "name   = ${name}"
echo "option = ${option}"


# > ./test --name testname
# name   = testname
# option = default_o


# > ./test --name testname -o test_o
# name   = testname
# option = test_o
